
deploy: chaiHttp
  provider: heroku
  api_key:
    secure: ZoTOgyyJgRBX0WSoI8ZOVrUSR9jTYViHJ3eK6oVbFg2L/yobZgXuFehFi715Xx2QhApWPXEih/G89lumImlP1CJbXgFsU6xt1qzLCH/naNRqnNzSaVlrLBlldsojrUfmdKT+yAzcTDehPdlGEVIao0UCTZzUDpImqLESAulGV90HE+raFAHIq01k/gsDEKyyhk+5wPa82Au1NjebVx2DWrIhrz3KU3YpnoqaNzsVmvEEB5WuTqcf8kaURZdDgx7NUapZHd/PykDs92jbd03q1s5orb+KJZ7eYXMlckZqkp2rzPQszcwYzi4F+3cCSki3c2reJ/LggNACgOzoYPl4dp+dAueb0HujTTDk+ufMJy7os1rEdtFxIPq3rYmeNf76bTj+URxfT/bbLFiLZN8klmhUb+kdXLzpOI09kTGVDfllkuNHiejTzyytE+P+7ExWA4Gg8ExLVGtPwLInr6jAX5CrU2oVn15agd3lTKTednMawZMh3RJo2qwp6JUqnnOWCS4fTEIVrIAAnd5u8GgoGzTvu22PEiO2lWrgi2xW22pI/j2MLa/GbEzSiYq6Tnuqsl+yvXRJyDdWIIhXhIiStvgxUWg2+mbz5OhH++BjVz/imHkZmq0X3NprgC/zN+kH3Quh2l7ndHOW2THC4Hdo3b3wRXo0Tw0DKvTO1xSXp2c=
  app: chaiHttp
  on:
    repo: sweick23/chaiHttp
